-- ─────────────────────────────────────────────────────────
-- DELIVERY_ORDERS 추가 데이터 INSERT
-- 통계 개념(모집단/표본) 체감을 위해 데이터 양을 늘립니다.
-- ─────────────────────────────────────────────────────────

INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 8500, 4.3, '강남구', DATE '2026-08-08');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('순대', '분식', 7000, 4.1, '서초구', DATE '2026-08-08');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 21000, 4.7, '강남구', DATE '2026-08-09');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('양념치킨', '치킨', 23000, 4.9, '송파구', DATE '2026-08-09');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('반반치킨', '치킨', 22000, 4.6, '서초구', DATE '2026-08-10');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 24000, 4.0, '강남구', DATE '2026-08-10');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('포테이토피자', '피자', 27000, 4.4, '송파구', DATE '2026-08-11');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('불고기피자', '피자', 26000, 4.3, '서초구', DATE '2026-08-11');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짜장면', '중식', 7500, 3.9, '강남구', DATE '2026-08-12');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짬뽕', '중식', 9000, 4.2, '송파구', DATE '2026-08-12');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('마라탕', '중식', 12500, 4.5, '강남구', DATE '2026-08-13');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('탕수육', '중식', 19000, 4.6, '서초구', DATE '2026-08-13');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('돈까스', '일식', 10500, 4.2, '송파구', DATE '2026-08-14');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('초밥세트', '일식', 28000, 4.8, '강남구', DATE '2026-08-14');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('우동', '일식', 8000, 4.0, '서초구', DATE '2026-08-15');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('라멘', '일식', 11000, 4.4, '송파구', DATE '2026-08-15');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 9500, 4.6, '서초구', DATE '2026-08-16');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('김밥', '분식', 5000, 4.0, '강남구', DATE '2026-08-16');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 22000, 4.5, '송파구', DATE '2026-08-17');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 25500, 4.1, '강남구', DATE '2026-08-17');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짜장면', '중식', 8000, 4.1, '서초구', DATE '2026-08-18');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('돈까스', '일식', 11500, 4.3, '송파구', DATE '2026-08-18');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('마라탕', '중식', 13500, 4.7, '강남구', DATE '2026-08-19');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('초밥세트', '일식', 29000, 4.9, '서초구', DATE '2026-08-19');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('떡볶이', '분식', 9000, 4.4, '송파구', DATE '2026-08-20');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('치킨', '치킨', 23500, 4.8, '강남구', DATE '2026-08-20');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('피자', '피자', 26500, 4.2, '서초구', DATE '2026-08-21');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('짬뽕', '중식', 9500, 4.3, '송파구', DATE '2026-08-21');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('우동', '일식', 8500, 4.1, '강남구', DATE '2026-08-22');
INSERT INTO DELIVERY_ORDERS (MENU_NAME, CATEGORY, PRICE, RATING, REGION, ORDER_DATE) VALUES ('김밥', '분식', 5500, 4.2, '서초구', DATE '2026-08-22');

COMMIT;
